# Generated by Django 4.0.3 on 2023-08-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_binvo_shoe_bin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='binvo',
            old_name='section_number',
            new_name='bin_number',
        ),
        migrations.RenameField(
            model_name='binvo',
            old_name='shelf_number',
            new_name='bin_size',
        ),
    ]
